### ISSUE TITLE
msc-gui GitHub Permissions

### ISSUE THREAD

**Issue by zanix** [MinecraftServerControl/msc-gui#6]
I don't seem to have the same permissions as I do over on the mscs repository. For example, I don't have mod privileges over issues so I cannot assign labels or create milestones.

**Comment by sandain** [comment]
I played around with the settings, do you have access now?

**Comment by zanix** [comment]
Yes, I can assign people, labels, and milestones now. I think we are set.

**Comment by sandain** [comment]
Awesome. Closed.
