### ISSUE TITLE
Invalid self-closing script tags

### ISSUE THREAD

**Issue by jonicho** [MinecraftServerControl/msc-gui#8]
In commit 2bb765041fcb7a036d1ada6b9ee34e61af314658 the script tags were changed to self-closing script tags, which are invalid, so that the mscs-gui is only a white window.

**Comment by sandain** [comment]
Ohh shoot. I noticed that and thought that I immediately committed a fix. I just logged on to my development box and submitted the fix with commit fbfafaf6521f4695955f53ea018d41c1ed0434f0. Thanks for the bug report.
