### ISSUE TITLE
Time-out error when connecting from an external system

### ISSUE THREAD

**Issue by Njensen6** [MinecraftServerControl/msc-gui#9]
I followed what instructions there were for setting up msc-gui and after configuring port forwarding and my firewalls to allow 8080, I get the screen below and the time-out error after 3 seconds. 

Any ideas what I missed? Any update on a more updated installation guide for the gui, as well? 
![msc-gui time-out error](https://user-images.githubusercontent.com/64370320/145289949-20983c48-3992-4769-af9c-3b9b9d1c354c.PNG)
?

**Comment by sandain** [comment]
Hi @Njensen6. No development has happened on this GUI project in over 2 years unfortunately. I've been too busy to work on it personally, and no one else has picked up the slack.  With that said, it is somewhat functional.  I just installed it on my minecraft server using the `make install` method, and it worked after I added a missing dependency by running `apt install libmojolicious-perl`.

As to why it is not working for you... 
* Do you have mscs and msc-gui installed on the same system?
* Can you run `mscs status` on that system and get valid results?
* Did you modify the username that mscs uses to run? Both msc-gui and mscs need to be run using the same user (default is `minecraft`).

If you get this working and feel like contributing to the project, I would be happy for the help.

**Comment by Njensen6** [comment]
@sandain 
I also ran the `make install`, and added the missing dependency as well.

> * Do you have mscs and msc-gui installed on the same system?
> * Can you run `mscs status` on that system and get valid results?
> * Did you modify the username that mscs uses to run? Both msc-gui and mscs need to be run using the same user (default is `minecraft`).

They are both on the same system, RPi 4 running Ubuntu Server 20.04
I can; I also verified that msc-gui is reporting active
![msc-gui time-out error 2](https://user-images.githubusercontent.com/64370320/145424656-11cf4e45-ccb3-4436-9151-861ce365a10a.PNG)
I did not modify the `minecraft` user at all. I also verified that `minecraft` is the owner of the entire `mscs` directory at `/opt/mscs`.

I am going to keep playing around with it, I may even remove msc-gui and redo the `make install` process just to cover all my bases if I cannot get it working. This (and MCSC) is an awesome project btw, and I will contribute whatever I can.

**Comment by sandain** [comment]
Maybe your mscs install is too old?  Try running `mscs status-json` to verify that you have the function that is actually used by msc-gui (I forgot that it doesn't use `mscs status`). I don't know, I'm reaching at straws here.

**Comment by Njensen6** [comment]
Sorry for the long delay in reply here; I figured out the issue. It was not the program at all. I forgot that I have a DDNS setup, so as soon as I changed from `http://<serverIP>:8080` to `http://<DDNS>:8080` it worked like a charm with the port forwarding I set up. Thank you for the assistance!
